//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claymore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleMechModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BattleMechModel()
        {
            this.BattleMeches = new HashSet<BattleMech>();
        }
    
        public System.Guid Id { get; set; }
        public string ModelNumber { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual BattleforceStats BattleforceStat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattleMech> BattleMeches { get; set; }
    }
}
