//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claymore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleMechBattleForceStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BattleMechBattleForceStatus()
        {
            this.Armor = 0;
            this.Structure = 0;
            this.EngineHits = 0;
            this.FireControlHits = 0;
            this.MPHits = 0;
            this.WeaponsHits = 0;
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int Armor { get; set; }
        public int Structure { get; set; }
        public int EngineHits { get; set; }
        public int FireControlHits { get; set; }
        public int MPHits { get; set; }
        public int WeaponsHits { get; set; }
        public System.Guid BattleMechId { get; set; }
    
        public virtual BattleMech BattleMech { get; set; }
    }
}
