//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claymore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleforceStats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BattleforceStats()
        {
            this.MovementAbilities = new HashSet<MovementAbility>();
            this.BattleforceStatsSpecialAbilities = new HashSet<BattleforceStatsSpecialAbility>();
        }
    
        public System.Guid Id { get; set; }
        public int Size { get; set; }
        public int ShortRangeDamage { get; set; }
        public int MediumRangeDamage { get; set; }
        public int LongRangeDamage { get; set; }
        public int OverheatValue { get; set; }
        public int Armor { get; set; }
        public int Structure { get; set; }
        public int PV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementAbility> MovementAbilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattleforceStatsSpecialAbility> BattleforceStatsSpecialAbilities { get; set; }
        public virtual BattleMechModel BattleMechModel { get; set; }
    }
}
