//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claymore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid Id { get; set; }
        public string PostDate { get; set; }
        public string Content { get; set; }
        public Nullable<System.Guid> CreditCharacterId { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Session Session { get; set; }
    }
}
