//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claymore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementAbility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovementAbility()
        {
            this.Amount = 0;
        }
    
        public System.Guid Id { get; set; }
        public System.Guid MovementTypeId { get; set; }
        public Nullable<System.Guid> BattleforceStatsId { get; set; }
        public int Amount { get; set; }
    
        public virtual MovementType MovementType { get; set; }
        public virtual BattleforceStats BattleforceStat { get; set; }
    }
}
